### ISSUE TITLE
Can't Browse remote SMB shares on OSX.

### ISSUE THREAD

**Issue by connectedway** [dcerpc/dcerpc#1]
I am having an issue connecting to a specific SMB server from OSX El Capitan (10.11.6).  I am able to connect to and browse shares on other servers.  So, I am trying to figure out what is wrong with the problem SMB server.  I'm assuming this library is used on OSX due to the error code that appears in the console log.  See below.

I have traced the session traffic between OSX and both these servers and the traffic looks good, and mostly similar, yet OSX will not issue the DCE bind request to srvsvc in the bad case.  Rather it will negotiate the session, connect to the IPC share, open the srvsvc pipe, but then promptly disconnects from the share.

I am trying to connect using the Finder and "Connect to Server...".  In the failure case, I will receive the following popup:

"there was a problem connecting to the server "badserver".

"There are no shares available or you are not allowed to access them on the server.  Please contact your system administrator to resolve the problem"

If I look at the console log messages, there is one clue:

8/29/16 9:50:36.072 AM NetAuthSysAgent[74269]: RPC to srvsrvc gave error 0x16c9a034

Some research points to the error 0x16c9034 being a rpc_s_cannot_connect.  Unfortunately, not very helpful.

The perplexing part is that the OSX stack has found the server, successfully authenticated, mounted the IPC share, AND opened the srvsvc file.  But fails to issue the Bind request and netshareenum.  I am not sure why it cannot connect although I have a suspicion.  I am hoping somone has some experience with the SMB stack in OSX.  I'm assuming it's the LikeWise stack (PBIS) from powerbroker and I've browsed through that code looking for clues but I end up lost in the weeds.

I can't upload the wireshark pcap files but I can email them if someone wants to take a look.  I'll discuss them here instead.

In the Good scenario, I see:
1. Negotiate Request
2. Negotiate Response (success)
3. Setup Request
4. Setup Response (more processing required)
5. Setup Request
6. Setup Response (success)
7. Tree Connect (IPC)
8. Tree Connect Response (success)
9. Create Request (srvsvc)
10. Create Response (success)
11. DCE Bind Request
12. DCE Bind Response
13. NetShareEnum Request
14. NetShareEnum Response

In the Bad scenario, I see the following:
1. Negotiate Request (same as good scenario)
2. Negotiate Response (similar, but not returning a security blob.  Not negotiating GSSAPI/SPNEGO)
3. Setup Request (same as good scenario)
4. Setup Response (more processing required, and with NTLMv2 security blob.  Not wrapped in GSSAPI/SPNEGO)
5. Setup Request (valid NTLMv2 Security Response)
6. Setup Response (success)
7. Tree Connect Request (IPC) (same as good scenario)
8. Tree Connect Response (success)
9. Create Request (srvsvc) (same as good scenario)
10. Create Response (success)
11. Tree Disconnect Request (IPC) (here is the question.  WHY???  Why won't it go forward with the bind request)
12. Tree Disconnect Response (success)

The hypothesis I have is that the OSX SMB stack will not send a bind request on a session that has not negotiated GSSAPI/SPNEGO.  Is that true?  Does anyone have any visibility into this?  Is there any way to enable more verbose logging of the stack?  Is there source code for the OSX stack that perhaps I could instrument to see what is going on.  I've tried to build dcerpc for OSX but it appears some updates are needed to get it to compile with the GSS framework supplied with OSX 10.11.6.

Any help is greatly appreciated.

**Comment by jpeach** [comment]
@connectedway You really need to file a bug with Apple at https://bugreport.apple.com.

**Comment by connectedway** [comment]
thanks jpeach.  I have submitted the bug report to Apple.  Thanks for the suggestion.

**Comment by connectedway** [comment]
Closing
