### ISSUE TITLE
buildconf is missing from the source

### ISSUE THREAD

**Issue by asmerovski** [dcerpc/dcerpc#15]
As per instructions for Linux:
To build on Linux or other UNIX-like systems, use the autotools build system.

~/dcerpc.git $ cd dcerpc
~/dcerpc.git $ ./buildconf
~/dcerpc.git $ ./configure && make
~/dcerpc.git $ sudo make install

buildconf is missing in the distribution, making this source code impossible to build on Linux.

**Comment by jpeach** [comment]
> On Dec 27, 2018, at 2:12 AM, asmerovski <notifications@github.com> wrote:
> 
> As per instructions for Linux:
> To build on Linux or other UNIX-like systems, use the autotools build system.
> 
> /dcerpc.git $ cd dcerpc
> **/dcerpc.git $ ./buildconf**
> ~/dcerpc.git $ ./configure && make
> ~/dcerpc.git $ sudo make install
> 
> buildconf is missing in the distribution, making this source code impossible to build on Linux.
> 
I’ll get the instructions updated, but you can just run “autoreconf -fi” instead

**Comment by asmerovski** [comment]
Thanks for resolving this one :)

**Comment by jpeach** [comment]
Updated the website instructions.
