### ISSUE TITLE
ms-bkrp.idl doesn't compile

### ISSUE THREAD

**Issue by MattChanda** [dcerpc/dcerpc#20]
I doesn't like the comma in size_is here: `[out, size_is(,*pcbDataOut)]    byte**      ppDataOut,` and gives this error: `The size attributes do not match the array dimension`.  

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-bkrp/9dc083a6-541f-47ef-aa05-afc4891aa1dc

Any suggestions for a workaround? or alternative syntax that would work?

**Comment by jpeach** [comment]
> I doesn't like the comma in size_is here: `[out, size_is(,*pcbDataOut)]    byte**      ppDataOut,` and gives this error: `The size attributes do not match the array dimension`.  
> 
> 
> 
> https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-bkrp/9dc083a6-541f-47ef-aa05-afc4891aa1dc
> 
> 
> 
> Any suggestions for a workaround? or alternative syntax that would work?

There used to be a few cases where MS used more modern syntax that could be transformed to the old DCE syntax, but I don't remember off the top of my head whether this is one. Try researching the old DCE docs or early MSRPC stuff to see whether there's an alternative.

**Comment by jpeach** [comment]
Microsoft IDL size_is: https://docs.microsoft.com/en-us/windows/win32/midl/size-is

IIUC then, `size_is(,*pcbDataOut)] byte** ppDataOut` means that the `pcbDataOut` specifies the second dimension of the `ppDataOut` array.

The DCE size_is spec says that it takes an `attr_var_list`, so it looks to me as though you need another output variable before the comma, maybe something like `size_is(*pcbDataOut1 ,*pcbDataOut2)] byte** ppDataOut`. I don't recall off the top of my head what the semantics of this would be. Maybe MSRPC defaults the size dimension to 1 if it isn't specified 🤷 

https://pubs.opengroup.org/onlinepubs/9629399/chap4.htm#tagcjh_08_02_18_04

**Comment by MattChanda** [comment]
Thanks, I’ll see what I can find.
