### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by moritz2** [dcerpc/dcerpc#8]
Hello, I tried to build the project on Mac OS X. But when I run the command `xcodebuild -configuration Debug -target dceidl` I get the error message `** BUILD FAILED **` with the description 

`/projects/dcerpc.git/BuildConfig/run-autoconf: line 130: ./buildconf: No such file or directory
run-autoconf: error:  buildconf failed`

I can't find a buildconf in the project. Is it missing?

**Comment by jpeach** [comment]
It looks like `buildconf` is missing, however it just runs `autoreconf -fi`. I'm not sure what state the Xcode project is in; you might want to just use the auto tools build directly, i.e.
```
$ autoreconf -fi
$ ./configure && make
```

**Comment by moritz2** [comment]
when I run `autoreconf -fi` then I get the following error

`configure.ac:128: warning: macro 'AM_DISABLE_STATIC' not found in library
configure.ac:135: warning: macro 'AM_PROG_LIBTOOL' not found in library
configure.ac:128: error: possibly undefined macro: AM_DISABLE_STATIC
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:135: error: possibly undefined macro: AM_PROG_LIBTOOL
autoreconf: /usr/local/Cellar/autoconf/2.69/bin/autoconf failed with exit status: 1
`

**Comment by jpeach** [comment]
You probably need to make sure you have a modern autoconf + automake + libtool installed.  You cane use home brew for that.

**Comment by moritz2** [comment]
oh yeah the libtool was missing. But now I get the error

`Making all in compat
make[1]: Nothing to be done for 'all'.
Making all in libdcethread
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
make[2]: Nothing to be done for 'all-am'.
Making all in idl_compiler
/usr/bin/bison -v   -p acf_yy -o acf_y.c -d acf_y.y
acf_y.y:284.14-21: syntax error, unexpected string, expecting =
make[1]: *** [acf_y.c] Error 1
make: *** [all-recursive] Error 1`

**Comment by MattHart-London** [comment]
A contributor introduced a couple of syntax errors.
Here's the fix
diff --git a/dcerpc/idl_compiler/acf_y.y b/dcerpc/idl_compiler/acf_y.y
index dd6014c..9d5bd2d 100644
--- a/dcerpc/idl_compiler/acf_y.y
+++ b/dcerpc/idl_compiler/acf_y.y
@@ -281,7 +281,7 @@ static void acf_warning
 %defines
 %error-verbose
 %pure-parser
-%name-prefix "acf_yy"
+%name-prefix="acf_yy"
 
 /* Tell Bison that the Flexer takes a yyscan_t parameter. */
 %lex-param { void * lexxer }
Tachyon-iMac:dcerpc administrator$ git diff dcerpc/idl_compiler/nidl_y.y
diff --git a/dcerpc/idl_compiler/nidl_y.y b/dcerpc/idl_compiler/nidl_y.y
index c2e4e28..c2e5922 100644
--- a/dcerpc/idl_compiler/nidl_y.y
+++ b/dcerpc/idl_compiler/nidl_y.y
@@ -133,7 +133,7 @@ static void nidl_yyerror (YYLTYPE *, nidl_parser_p, char const *);
 %defines
 %error-verbose
 %pure-parser
-%name-prefix "nidl_yy"
+%name-prefix="nidl_yy"
 
 /* Tell Bison that the Flexer takes a yyscan_t parameter. */
 %lex-param { void * lexxer }

**Comment by jpeach** [comment]
I'll try to look soon, but I didn't find any mention of the `=` syntax in the Bison docs. Do you have a reference?

**Comment by MattHart-London** [comment]
Apologies I probably should have checked the fix in myself.
I got the build errors, did a git blame and then saw that those two lines had been changed by a checkin back in March. If that hadn't worked I'd have tried to wade through the bison docs.

Matt
________________________________

**Comment by jpeach** [comment]
OK, you need a more recent `bison` than the macOS default. This works:
```
smelt:dcerpc jpeach$ brew install bison
...
smelt:dcerpc jpeach$ ./configure  BISON=$(brew --prefix bison)/bin/bison
...
smelt:dcerpc jpeach$ make
...
```

I'll update the build and docs.

**Comment by MattHart-London** [comment]
Thanks for fixing.

Matt
________________________________
